// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ignition/msgs/contact.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2fcontact_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2fcontact_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ignition/msgs/vector3d.pb.h"
#include "ignition/msgs/joint_wrench.pb.h"
#include "ignition/msgs/header.pb.h"
#ifndef _MSC_VER
#pragma GCC system_header
#else
#pragma warning(push)
#pragma warning(disable: 4244 4267 4100 4244 4512 4127 4068 4275 4251)
#endif
#include <memory>
#include <ignition/msgs/Export.hh>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ignition_2fmsgs_2fcontact_2eproto IGNITION_MSGS_VISIBLE
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct IGNITION_MSGS_VISIBLE TableStruct_ignition_2fmsgs_2fcontact_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern IGNITION_MSGS_VISIBLE const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ignition_2fmsgs_2fcontact_2eproto;
namespace ignition {
namespace msgs {
class Contact;
class ContactDefaultTypeInternal;
IGNITION_MSGS_VISIBLE extern ContactDefaultTypeInternal _Contact_default_instance_;
}  // namespace msgs
}  // namespace ignition
PROTOBUF_NAMESPACE_OPEN
template<> IGNITION_MSGS_VISIBLE ::ignition::msgs::Contact* Arena::CreateMaybeMessage<::ignition::msgs::Contact>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ignition {
namespace msgs {

// ===================================================================

class IGNITION_MSGS_VISIBLE Contact :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ignition.msgs.Contact) */ {
 public:
  Contact();
  virtual ~Contact();

  Contact(const Contact& from);
  Contact(Contact&& from) noexcept
    : Contact() {
    *this = ::std::move(from);
  }

  inline Contact& operator=(const Contact& from) {
    CopyFrom(from);
    return *this;
  }
  inline Contact& operator=(Contact&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Contact& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Contact* internal_default_instance() {
    return reinterpret_cast<const Contact*>(
               &_Contact_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Contact& a, Contact& b) {
    a.Swap(&b);
  }
  inline void Swap(Contact* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Contact* New() const final {
    return CreateMaybeMessage<Contact>(nullptr);
  }

  Contact* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Contact>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Contact& from);
  void MergeFrom(const Contact& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Contact* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ignition.msgs.Contact";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ignition_2fmsgs_2fcontact_2eproto);
    return ::descriptor_table_ignition_2fmsgs_2fcontact_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPositionFieldNumber = 4,
    kNormalFieldNumber = 5,
    kDepthFieldNumber = 6,
    kWrenchFieldNumber = 7,
    kCollision1FieldNumber = 2,
    kCollision2FieldNumber = 3,
    kWorldFieldNumber = 8,
    kHeaderFieldNumber = 1,
  };
  // repeated .ignition.msgs.Vector3d position = 4;
  int position_size() const;
  void clear_position();
  ::ignition::msgs::Vector3d* mutable_position(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ignition::msgs::Vector3d >*
      mutable_position();
  const ::ignition::msgs::Vector3d& position(int index) const;
  ::ignition::msgs::Vector3d* add_position();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ignition::msgs::Vector3d >&
      position() const;

  // repeated .ignition.msgs.Vector3d normal = 5;
  int normal_size() const;
  void clear_normal();
  ::ignition::msgs::Vector3d* mutable_normal(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ignition::msgs::Vector3d >*
      mutable_normal();
  const ::ignition::msgs::Vector3d& normal(int index) const;
  ::ignition::msgs::Vector3d* add_normal();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ignition::msgs::Vector3d >&
      normal() const;

  // repeated double depth = 6;
  int depth_size() const;
  void clear_depth();
  double depth(int index) const;
  void set_depth(int index, double value);
  void add_depth(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      depth() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_depth();

  // repeated .ignition.msgs.JointWrench wrench = 7;
  int wrench_size() const;
  void clear_wrench();
  ::ignition::msgs::JointWrench* mutable_wrench(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ignition::msgs::JointWrench >*
      mutable_wrench();
  const ::ignition::msgs::JointWrench& wrench(int index) const;
  ::ignition::msgs::JointWrench* add_wrench();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ignition::msgs::JointWrench >&
      wrench() const;

  // optional string collision1 = 2 [default = ""];
  bool has_collision1() const;
  void clear_collision1();
  const std::string& collision1() const;
  void set_collision1(const std::string& value);
  void set_collision1(std::string&& value);
  void set_collision1(const char* value);
  void set_collision1(const char* value, size_t size);
  std::string* mutable_collision1();
  std::string* release_collision1();
  void set_allocated_collision1(std::string* collision1);

  // optional string collision2 = 3 [default = ""];
  bool has_collision2() const;
  void clear_collision2();
  const std::string& collision2() const;
  void set_collision2(const std::string& value);
  void set_collision2(std::string&& value);
  void set_collision2(const char* value);
  void set_collision2(const char* value, size_t size);
  std::string* mutable_collision2();
  std::string* release_collision2();
  void set_allocated_collision2(std::string* collision2);

  // optional string world = 8 [default = "default"];
  bool has_world() const;
  void clear_world();
  const std::string& world() const;
  void set_world(const std::string& value);
  void set_world(std::string&& value);
  void set_world(const char* value);
  void set_world(const char* value, size_t size);
  std::string* mutable_world();
  std::string* release_world();
  void set_allocated_world(std::string* world);

  // optional .ignition.msgs.Header header = 1;
  bool has_header() const;
  void clear_header();
  const ::ignition::msgs::Header& header() const;
  ::ignition::msgs::Header* release_header();
  ::ignition::msgs::Header* mutable_header();
  void set_allocated_header(::ignition::msgs::Header* header);

  // @@protoc_insertion_point(class_scope:ignition.msgs.Contact)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ignition::msgs::Vector3d > position_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ignition::msgs::Vector3d > normal_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > depth_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ignition::msgs::JointWrench > wrench_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr collision1_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr collision2_;
  public:
  static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> _i_give_permission_to_break_this_code_default_world_;
  private:
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr world_;
  ::ignition::msgs::Header* header_;
  friend struct ::TableStruct_ignition_2fmsgs_2fcontact_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Contact

// optional .ignition.msgs.Header header = 1;
inline bool Contact::has_header() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline const ::ignition::msgs::Header& Contact::header() const {
  const ::ignition::msgs::Header* p = header_;
  // @@protoc_insertion_point(field_get:ignition.msgs.Contact.header)
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::Header*>(
      &::ignition::msgs::_Header_default_instance_);
}
inline ::ignition::msgs::Header* Contact::release_header() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Contact.header)
  _has_bits_[0] &= ~0x00000008u;
  ::ignition::msgs::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::ignition::msgs::Header* Contact::mutable_header() {
  _has_bits_[0] |= 0x00000008u;
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::Header>(GetArenaNoVirtual());
    header_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Contact.header)
  return header_;
}
inline void Contact::set_allocated_header(::ignition::msgs::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Contact.header)
}

// optional string collision1 = 2 [default = ""];
inline bool Contact::has_collision1() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Contact::clear_collision1() {
  collision1_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Contact::collision1() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Contact.collision1)
  return collision1_.GetNoArena();
}
inline void Contact::set_collision1(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  collision1_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Contact.collision1)
}
inline void Contact::set_collision1(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  collision1_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ignition.msgs.Contact.collision1)
}
inline void Contact::set_collision1(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  collision1_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ignition.msgs.Contact.collision1)
}
inline void Contact::set_collision1(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  collision1_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ignition.msgs.Contact.collision1)
}
inline std::string* Contact::mutable_collision1() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Contact.collision1)
  return collision1_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Contact::release_collision1() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Contact.collision1)
  if (!has_collision1()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return collision1_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Contact::set_allocated_collision1(std::string* collision1) {
  if (collision1 != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  collision1_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), collision1);
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Contact.collision1)
}

// optional string collision2 = 3 [default = ""];
inline bool Contact::has_collision2() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Contact::clear_collision2() {
  collision2_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Contact::collision2() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Contact.collision2)
  return collision2_.GetNoArena();
}
inline void Contact::set_collision2(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  collision2_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Contact.collision2)
}
inline void Contact::set_collision2(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  collision2_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ignition.msgs.Contact.collision2)
}
inline void Contact::set_collision2(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  collision2_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ignition.msgs.Contact.collision2)
}
inline void Contact::set_collision2(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  collision2_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ignition.msgs.Contact.collision2)
}
inline std::string* Contact::mutable_collision2() {
  _has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Contact.collision2)
  return collision2_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Contact::release_collision2() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Contact.collision2)
  if (!has_collision2()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return collision2_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Contact::set_allocated_collision2(std::string* collision2) {
  if (collision2 != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  collision2_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), collision2);
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Contact.collision2)
}

// repeated .ignition.msgs.Vector3d position = 4;
inline int Contact::position_size() const {
  return position_.size();
}
inline ::ignition::msgs::Vector3d* Contact::mutable_position(int index) {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Contact.position)
  return position_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ignition::msgs::Vector3d >*
Contact::mutable_position() {
  // @@protoc_insertion_point(field_mutable_list:ignition.msgs.Contact.position)
  return &position_;
}
inline const ::ignition::msgs::Vector3d& Contact::position(int index) const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Contact.position)
  return position_.Get(index);
}
inline ::ignition::msgs::Vector3d* Contact::add_position() {
  // @@protoc_insertion_point(field_add:ignition.msgs.Contact.position)
  return position_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ignition::msgs::Vector3d >&
Contact::position() const {
  // @@protoc_insertion_point(field_list:ignition.msgs.Contact.position)
  return position_;
}

// repeated .ignition.msgs.Vector3d normal = 5;
inline int Contact::normal_size() const {
  return normal_.size();
}
inline ::ignition::msgs::Vector3d* Contact::mutable_normal(int index) {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Contact.normal)
  return normal_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ignition::msgs::Vector3d >*
Contact::mutable_normal() {
  // @@protoc_insertion_point(field_mutable_list:ignition.msgs.Contact.normal)
  return &normal_;
}
inline const ::ignition::msgs::Vector3d& Contact::normal(int index) const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Contact.normal)
  return normal_.Get(index);
}
inline ::ignition::msgs::Vector3d* Contact::add_normal() {
  // @@protoc_insertion_point(field_add:ignition.msgs.Contact.normal)
  return normal_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ignition::msgs::Vector3d >&
Contact::normal() const {
  // @@protoc_insertion_point(field_list:ignition.msgs.Contact.normal)
  return normal_;
}

// repeated double depth = 6;
inline int Contact::depth_size() const {
  return depth_.size();
}
inline void Contact::clear_depth() {
  depth_.Clear();
}
inline double Contact::depth(int index) const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Contact.depth)
  return depth_.Get(index);
}
inline void Contact::set_depth(int index, double value) {
  depth_.Set(index, value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Contact.depth)
}
inline void Contact::add_depth(double value) {
  depth_.Add(value);
  // @@protoc_insertion_point(field_add:ignition.msgs.Contact.depth)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
Contact::depth() const {
  // @@protoc_insertion_point(field_list:ignition.msgs.Contact.depth)
  return depth_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
Contact::mutable_depth() {
  // @@protoc_insertion_point(field_mutable_list:ignition.msgs.Contact.depth)
  return &depth_;
}

// repeated .ignition.msgs.JointWrench wrench = 7;
inline int Contact::wrench_size() const {
  return wrench_.size();
}
inline ::ignition::msgs::JointWrench* Contact::mutable_wrench(int index) {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Contact.wrench)
  return wrench_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ignition::msgs::JointWrench >*
Contact::mutable_wrench() {
  // @@protoc_insertion_point(field_mutable_list:ignition.msgs.Contact.wrench)
  return &wrench_;
}
inline const ::ignition::msgs::JointWrench& Contact::wrench(int index) const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Contact.wrench)
  return wrench_.Get(index);
}
inline ::ignition::msgs::JointWrench* Contact::add_wrench() {
  // @@protoc_insertion_point(field_add:ignition.msgs.Contact.wrench)
  return wrench_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ignition::msgs::JointWrench >&
Contact::wrench() const {
  // @@protoc_insertion_point(field_list:ignition.msgs.Contact.wrench)
  return wrench_;
}

// optional string world = 8 [default = "default"];
inline bool Contact::has_world() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Contact::clear_world() {
  world_.ClearToDefaultNoArena(&::ignition::msgs::Contact::_i_give_permission_to_break_this_code_default_world_.get());
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& Contact::world() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Contact.world)
  return world_.GetNoArena();
}
inline void Contact::set_world(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  world_.SetNoArena(&::ignition::msgs::Contact::_i_give_permission_to_break_this_code_default_world_.get(), value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Contact.world)
}
inline void Contact::set_world(std::string&& value) {
  _has_bits_[0] |= 0x00000004u;
  world_.SetNoArena(
    &::ignition::msgs::Contact::_i_give_permission_to_break_this_code_default_world_.get(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ignition.msgs.Contact.world)
}
inline void Contact::set_world(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000004u;
  world_.SetNoArena(&::ignition::msgs::Contact::_i_give_permission_to_break_this_code_default_world_.get(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ignition.msgs.Contact.world)
}
inline void Contact::set_world(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000004u;
  world_.SetNoArena(&::ignition::msgs::Contact::_i_give_permission_to_break_this_code_default_world_.get(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ignition.msgs.Contact.world)
}
inline std::string* Contact::mutable_world() {
  _has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Contact.world)
  return world_.MutableNoArena(&::ignition::msgs::Contact::_i_give_permission_to_break_this_code_default_world_.get());
}
inline std::string* Contact::release_world() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Contact.world)
  if (!has_world()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return world_.ReleaseNonDefaultNoArena(&::ignition::msgs::Contact::_i_give_permission_to_break_this_code_default_world_.get());
}
inline void Contact::set_allocated_world(std::string* world) {
  if (world != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  world_.SetAllocatedNoArena(&::ignition::msgs::Contact::_i_give_permission_to_break_this_code_default_world_.get(), world);
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Contact.world)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

typedef std::unique_ptr<Contact> ContactUniquePtr;
typedef std::unique_ptr<const Contact> ConstContactUniquePtr;
typedef std::shared_ptr<Contact> ContactSharedPtr;
typedef std::shared_ptr<const Contact> ConstContactSharedPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace ignition

#ifdef _MSC_VER
#pragma warning(pop)
#endif
// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2fcontact_2eproto
