// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ignition/msgs/fog.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2ffog_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2ffog_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "ignition/msgs/color.pb.h"
#include "ignition/msgs/header.pb.h"
#ifndef _MSC_VER
#pragma GCC system_header
#else
#pragma warning(push)
#pragma warning(disable: 4244 4267 4100 4244 4512 4127 4068 4275 4251)
#endif
#include <memory>
#include <ignition/msgs/Export.hh>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ignition_2fmsgs_2ffog_2eproto IGNITION_MSGS_VISIBLE
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct IGNITION_MSGS_VISIBLE TableStruct_ignition_2fmsgs_2ffog_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern IGNITION_MSGS_VISIBLE const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ignition_2fmsgs_2ffog_2eproto;
namespace ignition {
namespace msgs {
class Fog;
class FogDefaultTypeInternal;
IGNITION_MSGS_VISIBLE extern FogDefaultTypeInternal _Fog_default_instance_;
}  // namespace msgs
}  // namespace ignition
PROTOBUF_NAMESPACE_OPEN
template<> IGNITION_MSGS_VISIBLE ::ignition::msgs::Fog* Arena::CreateMaybeMessage<::ignition::msgs::Fog>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ignition {
namespace msgs {

enum Fog_FogType : int {
  Fog_FogType_NONE = 1,
  Fog_FogType_LINEAR = 2,
  Fog_FogType_EXPONENTIAL = 3,
  Fog_FogType_EXPONENTIAL2 = 4
};
IGNITION_MSGS_VISIBLE bool Fog_FogType_IsValid(int value);
constexpr Fog_FogType Fog_FogType_FogType_MIN = Fog_FogType_NONE;
constexpr Fog_FogType Fog_FogType_FogType_MAX = Fog_FogType_EXPONENTIAL2;
constexpr int Fog_FogType_FogType_ARRAYSIZE = Fog_FogType_FogType_MAX + 1;

IGNITION_MSGS_VISIBLE const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Fog_FogType_descriptor();
template<typename T>
inline const std::string& Fog_FogType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Fog_FogType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Fog_FogType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Fog_FogType_descriptor(), enum_t_value);
}
inline bool Fog_FogType_Parse(
    const std::string& name, Fog_FogType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Fog_FogType>(
    Fog_FogType_descriptor(), name, value);
}
// ===================================================================

class IGNITION_MSGS_VISIBLE Fog :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ignition.msgs.Fog) */ {
 public:
  Fog();
  virtual ~Fog();

  Fog(const Fog& from);
  Fog(Fog&& from) noexcept
    : Fog() {
    *this = ::std::move(from);
  }

  inline Fog& operator=(const Fog& from) {
    CopyFrom(from);
    return *this;
  }
  inline Fog& operator=(Fog&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Fog& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Fog* internal_default_instance() {
    return reinterpret_cast<const Fog*>(
               &_Fog_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Fog& a, Fog& b) {
    a.Swap(&b);
  }
  inline void Swap(Fog* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Fog* New() const final {
    return CreateMaybeMessage<Fog>(nullptr);
  }

  Fog* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Fog>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Fog& from);
  void MergeFrom(const Fog& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Fog* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ignition.msgs.Fog";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ignition_2fmsgs_2ffog_2eproto);
    return ::descriptor_table_ignition_2fmsgs_2ffog_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Fog_FogType FogType;
  static constexpr FogType NONE =
    Fog_FogType_NONE;
  static constexpr FogType LINEAR =
    Fog_FogType_LINEAR;
  static constexpr FogType EXPONENTIAL =
    Fog_FogType_EXPONENTIAL;
  static constexpr FogType EXPONENTIAL2 =
    Fog_FogType_EXPONENTIAL2;
  static inline bool FogType_IsValid(int value) {
    return Fog_FogType_IsValid(value);
  }
  static constexpr FogType FogType_MIN =
    Fog_FogType_FogType_MIN;
  static constexpr FogType FogType_MAX =
    Fog_FogType_FogType_MAX;
  static constexpr int FogType_ARRAYSIZE =
    Fog_FogType_FogType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  FogType_descriptor() {
    return Fog_FogType_descriptor();
  }
  template<typename T>
  static inline const std::string& FogType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, FogType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function FogType_Name.");
    return Fog_FogType_Name(enum_t_value);
  }
  static inline bool FogType_Parse(const std::string& name,
      FogType* value) {
    return Fog_FogType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kHeaderFieldNumber = 1,
    kColorFieldNumber = 3,
    kDensityFieldNumber = 4,
    kStartFieldNumber = 5,
    kEndFieldNumber = 6,
    kTypeFieldNumber = 2,
  };
  // optional .ignition.msgs.Header header = 1;
  bool has_header() const;
  void clear_header();
  const ::ignition::msgs::Header& header() const;
  ::ignition::msgs::Header* release_header();
  ::ignition::msgs::Header* mutable_header();
  void set_allocated_header(::ignition::msgs::Header* header);

  // optional .ignition.msgs.Color color = 3;
  bool has_color() const;
  void clear_color();
  const ::ignition::msgs::Color& color() const;
  ::ignition::msgs::Color* release_color();
  ::ignition::msgs::Color* mutable_color();
  void set_allocated_color(::ignition::msgs::Color* color);

  // optional float density = 4;
  bool has_density() const;
  void clear_density();
  float density() const;
  void set_density(float value);

  // optional float start = 5;
  bool has_start() const;
  void clear_start();
  float start() const;
  void set_start(float value);

  // optional float end = 6;
  bool has_end() const;
  void clear_end();
  float end() const;
  void set_end(float value);

  // optional .ignition.msgs.Fog.FogType type = 2;
  bool has_type() const;
  void clear_type();
  ::ignition::msgs::Fog_FogType type() const;
  void set_type(::ignition::msgs::Fog_FogType value);

  // @@protoc_insertion_point(class_scope:ignition.msgs.Fog)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::ignition::msgs::Header* header_;
  ::ignition::msgs::Color* color_;
  float density_;
  float start_;
  float end_;
  int type_;
  friend struct ::TableStruct_ignition_2fmsgs_2ffog_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Fog

// optional .ignition.msgs.Header header = 1;
inline bool Fog::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline const ::ignition::msgs::Header& Fog::header() const {
  const ::ignition::msgs::Header* p = header_;
  // @@protoc_insertion_point(field_get:ignition.msgs.Fog.header)
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::Header*>(
      &::ignition::msgs::_Header_default_instance_);
}
inline ::ignition::msgs::Header* Fog::release_header() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Fog.header)
  _has_bits_[0] &= ~0x00000001u;
  ::ignition::msgs::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::ignition::msgs::Header* Fog::mutable_header() {
  _has_bits_[0] |= 0x00000001u;
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::Header>(GetArenaNoVirtual());
    header_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Fog.header)
  return header_;
}
inline void Fog::set_allocated_header(::ignition::msgs::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Fog.header)
}

// optional .ignition.msgs.Fog.FogType type = 2;
inline bool Fog::has_type() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Fog::clear_type() {
  type_ = 1;
  _has_bits_[0] &= ~0x00000020u;
}
inline ::ignition::msgs::Fog_FogType Fog::type() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Fog.type)
  return static_cast< ::ignition::msgs::Fog_FogType >(type_);
}
inline void Fog::set_type(::ignition::msgs::Fog_FogType value) {
  assert(::ignition::msgs::Fog_FogType_IsValid(value));
  _has_bits_[0] |= 0x00000020u;
  type_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.Fog.type)
}

// optional .ignition.msgs.Color color = 3;
inline bool Fog::has_color() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline const ::ignition::msgs::Color& Fog::color() const {
  const ::ignition::msgs::Color* p = color_;
  // @@protoc_insertion_point(field_get:ignition.msgs.Fog.color)
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::Color*>(
      &::ignition::msgs::_Color_default_instance_);
}
inline ::ignition::msgs::Color* Fog::release_color() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Fog.color)
  _has_bits_[0] &= ~0x00000002u;
  ::ignition::msgs::Color* temp = color_;
  color_ = nullptr;
  return temp;
}
inline ::ignition::msgs::Color* Fog::mutable_color() {
  _has_bits_[0] |= 0x00000002u;
  if (color_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::Color>(GetArenaNoVirtual());
    color_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Fog.color)
  return color_;
}
inline void Fog::set_allocated_color(::ignition::msgs::Color* color) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(color_);
  }
  if (color) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      color = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, color, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  color_ = color;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Fog.color)
}

// optional float density = 4;
inline bool Fog::has_density() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Fog::clear_density() {
  density_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline float Fog::density() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Fog.density)
  return density_;
}
inline void Fog::set_density(float value) {
  _has_bits_[0] |= 0x00000004u;
  density_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.Fog.density)
}

// optional float start = 5;
inline bool Fog::has_start() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Fog::clear_start() {
  start_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline float Fog::start() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Fog.start)
  return start_;
}
inline void Fog::set_start(float value) {
  _has_bits_[0] |= 0x00000008u;
  start_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.Fog.start)
}

// optional float end = 6;
inline bool Fog::has_end() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Fog::clear_end() {
  end_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline float Fog::end() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Fog.end)
  return end_;
}
inline void Fog::set_end(float value) {
  _has_bits_[0] |= 0x00000010u;
  end_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.Fog.end)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

typedef std::unique_ptr<Fog> FogUniquePtr;
typedef std::unique_ptr<const Fog> ConstFogUniquePtr;
typedef std::shared_ptr<Fog> FogSharedPtr;
typedef std::shared_ptr<const Fog> ConstFogSharedPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace ignition

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::ignition::msgs::Fog_FogType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ignition::msgs::Fog_FogType>() {
  return ::ignition::msgs::Fog_FogType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

#ifdef _MSC_VER
#pragma warning(pop)
#endif
// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2ffog_2eproto
