// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ignition/msgs/gps_sensor.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2fgps_5fsensor_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2fgps_5fsensor_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ignition/msgs/sensor_noise.pb.h"
#include "ignition/msgs/header.pb.h"
#ifndef _MSC_VER
#pragma GCC system_header
#else
#pragma warning(push)
#pragma warning(disable: 4244 4267 4100 4244 4512 4127 4068 4275 4251)
#endif
#include <memory>
#include <ignition/msgs/Export.hh>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ignition_2fmsgs_2fgps_5fsensor_2eproto IGNITION_MSGS_VISIBLE
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct IGNITION_MSGS_VISIBLE TableStruct_ignition_2fmsgs_2fgps_5fsensor_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern IGNITION_MSGS_VISIBLE const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ignition_2fmsgs_2fgps_5fsensor_2eproto;
namespace ignition {
namespace msgs {
class GPSSensor;
class GPSSensorDefaultTypeInternal;
IGNITION_MSGS_VISIBLE extern GPSSensorDefaultTypeInternal _GPSSensor_default_instance_;
class GPSSensor_Sensing;
class GPSSensor_SensingDefaultTypeInternal;
IGNITION_MSGS_VISIBLE extern GPSSensor_SensingDefaultTypeInternal _GPSSensor_Sensing_default_instance_;
}  // namespace msgs
}  // namespace ignition
PROTOBUF_NAMESPACE_OPEN
template<> IGNITION_MSGS_VISIBLE ::ignition::msgs::GPSSensor* Arena::CreateMaybeMessage<::ignition::msgs::GPSSensor>(Arena*);
template<> IGNITION_MSGS_VISIBLE ::ignition::msgs::GPSSensor_Sensing* Arena::CreateMaybeMessage<::ignition::msgs::GPSSensor_Sensing>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ignition {
namespace msgs {

// ===================================================================

class IGNITION_MSGS_VISIBLE GPSSensor_Sensing :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ignition.msgs.GPSSensor.Sensing) */ {
 public:
  GPSSensor_Sensing();
  virtual ~GPSSensor_Sensing();

  GPSSensor_Sensing(const GPSSensor_Sensing& from);
  GPSSensor_Sensing(GPSSensor_Sensing&& from) noexcept
    : GPSSensor_Sensing() {
    *this = ::std::move(from);
  }

  inline GPSSensor_Sensing& operator=(const GPSSensor_Sensing& from) {
    CopyFrom(from);
    return *this;
  }
  inline GPSSensor_Sensing& operator=(GPSSensor_Sensing&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GPSSensor_Sensing& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GPSSensor_Sensing* internal_default_instance() {
    return reinterpret_cast<const GPSSensor_Sensing*>(
               &_GPSSensor_Sensing_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GPSSensor_Sensing& a, GPSSensor_Sensing& b) {
    a.Swap(&b);
  }
  inline void Swap(GPSSensor_Sensing* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GPSSensor_Sensing* New() const final {
    return CreateMaybeMessage<GPSSensor_Sensing>(nullptr);
  }

  GPSSensor_Sensing* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GPSSensor_Sensing>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GPSSensor_Sensing& from);
  void MergeFrom(const GPSSensor_Sensing& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GPSSensor_Sensing* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ignition.msgs.GPSSensor.Sensing";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ignition_2fmsgs_2fgps_5fsensor_2eproto);
    return ::descriptor_table_ignition_2fmsgs_2fgps_5fsensor_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHorizontalNoiseFieldNumber = 1,
    kVerticalNoiseFieldNumber = 2,
  };
  // optional .ignition.msgs.SensorNoise horizontal_noise = 1;
  bool has_horizontal_noise() const;
  void clear_horizontal_noise();
  const ::ignition::msgs::SensorNoise& horizontal_noise() const;
  ::ignition::msgs::SensorNoise* release_horizontal_noise();
  ::ignition::msgs::SensorNoise* mutable_horizontal_noise();
  void set_allocated_horizontal_noise(::ignition::msgs::SensorNoise* horizontal_noise);

  // optional .ignition.msgs.SensorNoise vertical_noise = 2;
  bool has_vertical_noise() const;
  void clear_vertical_noise();
  const ::ignition::msgs::SensorNoise& vertical_noise() const;
  ::ignition::msgs::SensorNoise* release_vertical_noise();
  ::ignition::msgs::SensorNoise* mutable_vertical_noise();
  void set_allocated_vertical_noise(::ignition::msgs::SensorNoise* vertical_noise);

  // @@protoc_insertion_point(class_scope:ignition.msgs.GPSSensor.Sensing)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::ignition::msgs::SensorNoise* horizontal_noise_;
  ::ignition::msgs::SensorNoise* vertical_noise_;
  friend struct ::TableStruct_ignition_2fmsgs_2fgps_5fsensor_2eproto;
};
// -------------------------------------------------------------------

class IGNITION_MSGS_VISIBLE GPSSensor :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ignition.msgs.GPSSensor) */ {
 public:
  GPSSensor();
  virtual ~GPSSensor();

  GPSSensor(const GPSSensor& from);
  GPSSensor(GPSSensor&& from) noexcept
    : GPSSensor() {
    *this = ::std::move(from);
  }

  inline GPSSensor& operator=(const GPSSensor& from) {
    CopyFrom(from);
    return *this;
  }
  inline GPSSensor& operator=(GPSSensor&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GPSSensor& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GPSSensor* internal_default_instance() {
    return reinterpret_cast<const GPSSensor*>(
               &_GPSSensor_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GPSSensor& a, GPSSensor& b) {
    a.Swap(&b);
  }
  inline void Swap(GPSSensor* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GPSSensor* New() const final {
    return CreateMaybeMessage<GPSSensor>(nullptr);
  }

  GPSSensor* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GPSSensor>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GPSSensor& from);
  void MergeFrom(const GPSSensor& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GPSSensor* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ignition.msgs.GPSSensor";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ignition_2fmsgs_2fgps_5fsensor_2eproto);
    return ::descriptor_table_ignition_2fmsgs_2fgps_5fsensor_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef GPSSensor_Sensing Sensing;

  // accessors -------------------------------------------------------

  enum : int {
    kHeaderFieldNumber = 1,
    kPositionFieldNumber = 2,
    kVelocityFieldNumber = 3,
  };
  // optional .ignition.msgs.Header header = 1;
  bool has_header() const;
  void clear_header();
  const ::ignition::msgs::Header& header() const;
  ::ignition::msgs::Header* release_header();
  ::ignition::msgs::Header* mutable_header();
  void set_allocated_header(::ignition::msgs::Header* header);

  // optional .ignition.msgs.GPSSensor.Sensing position = 2;
  bool has_position() const;
  void clear_position();
  const ::ignition::msgs::GPSSensor_Sensing& position() const;
  ::ignition::msgs::GPSSensor_Sensing* release_position();
  ::ignition::msgs::GPSSensor_Sensing* mutable_position();
  void set_allocated_position(::ignition::msgs::GPSSensor_Sensing* position);

  // optional .ignition.msgs.GPSSensor.Sensing velocity = 3;
  bool has_velocity() const;
  void clear_velocity();
  const ::ignition::msgs::GPSSensor_Sensing& velocity() const;
  ::ignition::msgs::GPSSensor_Sensing* release_velocity();
  ::ignition::msgs::GPSSensor_Sensing* mutable_velocity();
  void set_allocated_velocity(::ignition::msgs::GPSSensor_Sensing* velocity);

  // @@protoc_insertion_point(class_scope:ignition.msgs.GPSSensor)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::ignition::msgs::Header* header_;
  ::ignition::msgs::GPSSensor_Sensing* position_;
  ::ignition::msgs::GPSSensor_Sensing* velocity_;
  friend struct ::TableStruct_ignition_2fmsgs_2fgps_5fsensor_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GPSSensor_Sensing

// optional .ignition.msgs.SensorNoise horizontal_noise = 1;
inline bool GPSSensor_Sensing::has_horizontal_noise() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline const ::ignition::msgs::SensorNoise& GPSSensor_Sensing::horizontal_noise() const {
  const ::ignition::msgs::SensorNoise* p = horizontal_noise_;
  // @@protoc_insertion_point(field_get:ignition.msgs.GPSSensor.Sensing.horizontal_noise)
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::SensorNoise*>(
      &::ignition::msgs::_SensorNoise_default_instance_);
}
inline ::ignition::msgs::SensorNoise* GPSSensor_Sensing::release_horizontal_noise() {
  // @@protoc_insertion_point(field_release:ignition.msgs.GPSSensor.Sensing.horizontal_noise)
  _has_bits_[0] &= ~0x00000001u;
  ::ignition::msgs::SensorNoise* temp = horizontal_noise_;
  horizontal_noise_ = nullptr;
  return temp;
}
inline ::ignition::msgs::SensorNoise* GPSSensor_Sensing::mutable_horizontal_noise() {
  _has_bits_[0] |= 0x00000001u;
  if (horizontal_noise_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::SensorNoise>(GetArenaNoVirtual());
    horizontal_noise_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.GPSSensor.Sensing.horizontal_noise)
  return horizontal_noise_;
}
inline void GPSSensor_Sensing::set_allocated_horizontal_noise(::ignition::msgs::SensorNoise* horizontal_noise) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(horizontal_noise_);
  }
  if (horizontal_noise) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      horizontal_noise = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, horizontal_noise, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  horizontal_noise_ = horizontal_noise;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.GPSSensor.Sensing.horizontal_noise)
}

// optional .ignition.msgs.SensorNoise vertical_noise = 2;
inline bool GPSSensor_Sensing::has_vertical_noise() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline const ::ignition::msgs::SensorNoise& GPSSensor_Sensing::vertical_noise() const {
  const ::ignition::msgs::SensorNoise* p = vertical_noise_;
  // @@protoc_insertion_point(field_get:ignition.msgs.GPSSensor.Sensing.vertical_noise)
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::SensorNoise*>(
      &::ignition::msgs::_SensorNoise_default_instance_);
}
inline ::ignition::msgs::SensorNoise* GPSSensor_Sensing::release_vertical_noise() {
  // @@protoc_insertion_point(field_release:ignition.msgs.GPSSensor.Sensing.vertical_noise)
  _has_bits_[0] &= ~0x00000002u;
  ::ignition::msgs::SensorNoise* temp = vertical_noise_;
  vertical_noise_ = nullptr;
  return temp;
}
inline ::ignition::msgs::SensorNoise* GPSSensor_Sensing::mutable_vertical_noise() {
  _has_bits_[0] |= 0x00000002u;
  if (vertical_noise_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::SensorNoise>(GetArenaNoVirtual());
    vertical_noise_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.GPSSensor.Sensing.vertical_noise)
  return vertical_noise_;
}
inline void GPSSensor_Sensing::set_allocated_vertical_noise(::ignition::msgs::SensorNoise* vertical_noise) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(vertical_noise_);
  }
  if (vertical_noise) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      vertical_noise = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, vertical_noise, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  vertical_noise_ = vertical_noise;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.GPSSensor.Sensing.vertical_noise)
}

// -------------------------------------------------------------------

// GPSSensor

// optional .ignition.msgs.Header header = 1;
inline bool GPSSensor::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline const ::ignition::msgs::Header& GPSSensor::header() const {
  const ::ignition::msgs::Header* p = header_;
  // @@protoc_insertion_point(field_get:ignition.msgs.GPSSensor.header)
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::Header*>(
      &::ignition::msgs::_Header_default_instance_);
}
inline ::ignition::msgs::Header* GPSSensor::release_header() {
  // @@protoc_insertion_point(field_release:ignition.msgs.GPSSensor.header)
  _has_bits_[0] &= ~0x00000001u;
  ::ignition::msgs::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::ignition::msgs::Header* GPSSensor::mutable_header() {
  _has_bits_[0] |= 0x00000001u;
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::Header>(GetArenaNoVirtual());
    header_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.GPSSensor.header)
  return header_;
}
inline void GPSSensor::set_allocated_header(::ignition::msgs::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.GPSSensor.header)
}

// optional .ignition.msgs.GPSSensor.Sensing position = 2;
inline bool GPSSensor::has_position() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GPSSensor::clear_position() {
  if (position_ != nullptr) position_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::ignition::msgs::GPSSensor_Sensing& GPSSensor::position() const {
  const ::ignition::msgs::GPSSensor_Sensing* p = position_;
  // @@protoc_insertion_point(field_get:ignition.msgs.GPSSensor.position)
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::GPSSensor_Sensing*>(
      &::ignition::msgs::_GPSSensor_Sensing_default_instance_);
}
inline ::ignition::msgs::GPSSensor_Sensing* GPSSensor::release_position() {
  // @@protoc_insertion_point(field_release:ignition.msgs.GPSSensor.position)
  _has_bits_[0] &= ~0x00000002u;
  ::ignition::msgs::GPSSensor_Sensing* temp = position_;
  position_ = nullptr;
  return temp;
}
inline ::ignition::msgs::GPSSensor_Sensing* GPSSensor::mutable_position() {
  _has_bits_[0] |= 0x00000002u;
  if (position_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::GPSSensor_Sensing>(GetArenaNoVirtual());
    position_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.GPSSensor.position)
  return position_;
}
inline void GPSSensor::set_allocated_position(::ignition::msgs::GPSSensor_Sensing* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete position_;
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  position_ = position;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.GPSSensor.position)
}

// optional .ignition.msgs.GPSSensor.Sensing velocity = 3;
inline bool GPSSensor::has_velocity() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GPSSensor::clear_velocity() {
  if (velocity_ != nullptr) velocity_->Clear();
  _has_bits_[0] &= ~0x00000004u;
}
inline const ::ignition::msgs::GPSSensor_Sensing& GPSSensor::velocity() const {
  const ::ignition::msgs::GPSSensor_Sensing* p = velocity_;
  // @@protoc_insertion_point(field_get:ignition.msgs.GPSSensor.velocity)
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::GPSSensor_Sensing*>(
      &::ignition::msgs::_GPSSensor_Sensing_default_instance_);
}
inline ::ignition::msgs::GPSSensor_Sensing* GPSSensor::release_velocity() {
  // @@protoc_insertion_point(field_release:ignition.msgs.GPSSensor.velocity)
  _has_bits_[0] &= ~0x00000004u;
  ::ignition::msgs::GPSSensor_Sensing* temp = velocity_;
  velocity_ = nullptr;
  return temp;
}
inline ::ignition::msgs::GPSSensor_Sensing* GPSSensor::mutable_velocity() {
  _has_bits_[0] |= 0x00000004u;
  if (velocity_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::GPSSensor_Sensing>(GetArenaNoVirtual());
    velocity_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.GPSSensor.velocity)
  return velocity_;
}
inline void GPSSensor::set_allocated_velocity(::ignition::msgs::GPSSensor_Sensing* velocity) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete velocity_;
  }
  if (velocity) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      velocity = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, velocity, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  velocity_ = velocity;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.GPSSensor.velocity)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


typedef std::unique_ptr<GPSSensor> GPSSensorUniquePtr;
typedef std::unique_ptr<const GPSSensor> ConstGPSSensorUniquePtr;
typedef std::shared_ptr<GPSSensor> GPSSensorSharedPtr;
typedef std::shared_ptr<const GPSSensor> ConstGPSSensorSharedPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace ignition

#ifdef _MSC_VER
#pragma warning(pop)
#endif
// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2fgps_5fsensor_2eproto
