// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ignition/msgs/joint_wrench.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2fjoint_5fwrench_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2fjoint_5fwrench_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ignition/msgs/wrench.pb.h"
#include "ignition/msgs/header.pb.h"
#ifndef _MSC_VER
#pragma GCC system_header
#else
#pragma warning(push)
#pragma warning(disable: 4244 4267 4100 4244 4512 4127 4068 4275 4251)
#endif
#include <memory>
#include <ignition/msgs/Export.hh>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ignition_2fmsgs_2fjoint_5fwrench_2eproto IGNITION_MSGS_VISIBLE
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct IGNITION_MSGS_VISIBLE TableStruct_ignition_2fmsgs_2fjoint_5fwrench_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern IGNITION_MSGS_VISIBLE const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ignition_2fmsgs_2fjoint_5fwrench_2eproto;
namespace ignition {
namespace msgs {
class JointWrench;
class JointWrenchDefaultTypeInternal;
IGNITION_MSGS_VISIBLE extern JointWrenchDefaultTypeInternal _JointWrench_default_instance_;
}  // namespace msgs
}  // namespace ignition
PROTOBUF_NAMESPACE_OPEN
template<> IGNITION_MSGS_VISIBLE ::ignition::msgs::JointWrench* Arena::CreateMaybeMessage<::ignition::msgs::JointWrench>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ignition {
namespace msgs {

// ===================================================================

class IGNITION_MSGS_VISIBLE JointWrench :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ignition.msgs.JointWrench) */ {
 public:
  JointWrench();
  virtual ~JointWrench();

  JointWrench(const JointWrench& from);
  JointWrench(JointWrench&& from) noexcept
    : JointWrench() {
    *this = ::std::move(from);
  }

  inline JointWrench& operator=(const JointWrench& from) {
    CopyFrom(from);
    return *this;
  }
  inline JointWrench& operator=(JointWrench&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const JointWrench& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const JointWrench* internal_default_instance() {
    return reinterpret_cast<const JointWrench*>(
               &_JointWrench_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(JointWrench& a, JointWrench& b) {
    a.Swap(&b);
  }
  inline void Swap(JointWrench* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline JointWrench* New() const final {
    return CreateMaybeMessage<JointWrench>(nullptr);
  }

  JointWrench* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<JointWrench>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const JointWrench& from);
  void MergeFrom(const JointWrench& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JointWrench* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ignition.msgs.JointWrench";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ignition_2fmsgs_2fjoint_5fwrench_2eproto);
    return ::descriptor_table_ignition_2fmsgs_2fjoint_5fwrench_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBody1NameFieldNumber = 2,
    kBody2NameFieldNumber = 4,
    kHeaderFieldNumber = 1,
    kBody1WrenchFieldNumber = 6,
    kBody2WrenchFieldNumber = 7,
    kBody1IdFieldNumber = 3,
    kBody2IdFieldNumber = 5,
  };
  // optional string body_1_name = 2;
  bool has_body_1_name() const;
  void clear_body_1_name();
  const std::string& body_1_name() const;
  void set_body_1_name(const std::string& value);
  void set_body_1_name(std::string&& value);
  void set_body_1_name(const char* value);
  void set_body_1_name(const char* value, size_t size);
  std::string* mutable_body_1_name();
  std::string* release_body_1_name();
  void set_allocated_body_1_name(std::string* body_1_name);

  // optional string body_2_name = 4;
  bool has_body_2_name() const;
  void clear_body_2_name();
  const std::string& body_2_name() const;
  void set_body_2_name(const std::string& value);
  void set_body_2_name(std::string&& value);
  void set_body_2_name(const char* value);
  void set_body_2_name(const char* value, size_t size);
  std::string* mutable_body_2_name();
  std::string* release_body_2_name();
  void set_allocated_body_2_name(std::string* body_2_name);

  // optional .ignition.msgs.Header header = 1;
  bool has_header() const;
  void clear_header();
  const ::ignition::msgs::Header& header() const;
  ::ignition::msgs::Header* release_header();
  ::ignition::msgs::Header* mutable_header();
  void set_allocated_header(::ignition::msgs::Header* header);

  // optional .ignition.msgs.Wrench body_1_wrench = 6;
  bool has_body_1_wrench() const;
  void clear_body_1_wrench();
  const ::ignition::msgs::Wrench& body_1_wrench() const;
  ::ignition::msgs::Wrench* release_body_1_wrench();
  ::ignition::msgs::Wrench* mutable_body_1_wrench();
  void set_allocated_body_1_wrench(::ignition::msgs::Wrench* body_1_wrench);

  // optional .ignition.msgs.Wrench body_2_wrench = 7;
  bool has_body_2_wrench() const;
  void clear_body_2_wrench();
  const ::ignition::msgs::Wrench& body_2_wrench() const;
  ::ignition::msgs::Wrench* release_body_2_wrench();
  ::ignition::msgs::Wrench* mutable_body_2_wrench();
  void set_allocated_body_2_wrench(::ignition::msgs::Wrench* body_2_wrench);

  // optional uint32 body_1_id = 3;
  bool has_body_1_id() const;
  void clear_body_1_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 body_1_id() const;
  void set_body_1_id(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // optional uint32 body_2_id = 5;
  bool has_body_2_id() const;
  void clear_body_2_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 body_2_id() const;
  void set_body_2_id(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // @@protoc_insertion_point(class_scope:ignition.msgs.JointWrench)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr body_1_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr body_2_name_;
  ::ignition::msgs::Header* header_;
  ::ignition::msgs::Wrench* body_1_wrench_;
  ::ignition::msgs::Wrench* body_2_wrench_;
  ::PROTOBUF_NAMESPACE_ID::uint32 body_1_id_;
  ::PROTOBUF_NAMESPACE_ID::uint32 body_2_id_;
  friend struct ::TableStruct_ignition_2fmsgs_2fjoint_5fwrench_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// JointWrench

// optional .ignition.msgs.Header header = 1;
inline bool JointWrench::has_header() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline const ::ignition::msgs::Header& JointWrench::header() const {
  const ::ignition::msgs::Header* p = header_;
  // @@protoc_insertion_point(field_get:ignition.msgs.JointWrench.header)
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::Header*>(
      &::ignition::msgs::_Header_default_instance_);
}
inline ::ignition::msgs::Header* JointWrench::release_header() {
  // @@protoc_insertion_point(field_release:ignition.msgs.JointWrench.header)
  _has_bits_[0] &= ~0x00000004u;
  ::ignition::msgs::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::ignition::msgs::Header* JointWrench::mutable_header() {
  _has_bits_[0] |= 0x00000004u;
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::Header>(GetArenaNoVirtual());
    header_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.JointWrench.header)
  return header_;
}
inline void JointWrench::set_allocated_header(::ignition::msgs::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.JointWrench.header)
}

// optional string body_1_name = 2;
inline bool JointWrench::has_body_1_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void JointWrench::clear_body_1_name() {
  body_1_name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& JointWrench::body_1_name() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.JointWrench.body_1_name)
  return body_1_name_.GetNoArena();
}
inline void JointWrench::set_body_1_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  body_1_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ignition.msgs.JointWrench.body_1_name)
}
inline void JointWrench::set_body_1_name(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  body_1_name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ignition.msgs.JointWrench.body_1_name)
}
inline void JointWrench::set_body_1_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  body_1_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ignition.msgs.JointWrench.body_1_name)
}
inline void JointWrench::set_body_1_name(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  body_1_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ignition.msgs.JointWrench.body_1_name)
}
inline std::string* JointWrench::mutable_body_1_name() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:ignition.msgs.JointWrench.body_1_name)
  return body_1_name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* JointWrench::release_body_1_name() {
  // @@protoc_insertion_point(field_release:ignition.msgs.JointWrench.body_1_name)
  if (!has_body_1_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return body_1_name_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void JointWrench::set_allocated_body_1_name(std::string* body_1_name) {
  if (body_1_name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  body_1_name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), body_1_name);
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.JointWrench.body_1_name)
}

// optional uint32 body_1_id = 3;
inline bool JointWrench::has_body_1_id() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void JointWrench::clear_body_1_id() {
  body_1_id_ = 0u;
  _has_bits_[0] &= ~0x00000020u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 JointWrench::body_1_id() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.JointWrench.body_1_id)
  return body_1_id_;
}
inline void JointWrench::set_body_1_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000020u;
  body_1_id_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.JointWrench.body_1_id)
}

// optional string body_2_name = 4;
inline bool JointWrench::has_body_2_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void JointWrench::clear_body_2_name() {
  body_2_name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& JointWrench::body_2_name() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.JointWrench.body_2_name)
  return body_2_name_.GetNoArena();
}
inline void JointWrench::set_body_2_name(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  body_2_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ignition.msgs.JointWrench.body_2_name)
}
inline void JointWrench::set_body_2_name(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  body_2_name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ignition.msgs.JointWrench.body_2_name)
}
inline void JointWrench::set_body_2_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  body_2_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ignition.msgs.JointWrench.body_2_name)
}
inline void JointWrench::set_body_2_name(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  body_2_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ignition.msgs.JointWrench.body_2_name)
}
inline std::string* JointWrench::mutable_body_2_name() {
  _has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_mutable:ignition.msgs.JointWrench.body_2_name)
  return body_2_name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* JointWrench::release_body_2_name() {
  // @@protoc_insertion_point(field_release:ignition.msgs.JointWrench.body_2_name)
  if (!has_body_2_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return body_2_name_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void JointWrench::set_allocated_body_2_name(std::string* body_2_name) {
  if (body_2_name != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  body_2_name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), body_2_name);
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.JointWrench.body_2_name)
}

// optional uint32 body_2_id = 5;
inline bool JointWrench::has_body_2_id() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void JointWrench::clear_body_2_id() {
  body_2_id_ = 0u;
  _has_bits_[0] &= ~0x00000040u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 JointWrench::body_2_id() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.JointWrench.body_2_id)
  return body_2_id_;
}
inline void JointWrench::set_body_2_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000040u;
  body_2_id_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.JointWrench.body_2_id)
}

// optional .ignition.msgs.Wrench body_1_wrench = 6;
inline bool JointWrench::has_body_1_wrench() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline const ::ignition::msgs::Wrench& JointWrench::body_1_wrench() const {
  const ::ignition::msgs::Wrench* p = body_1_wrench_;
  // @@protoc_insertion_point(field_get:ignition.msgs.JointWrench.body_1_wrench)
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::Wrench*>(
      &::ignition::msgs::_Wrench_default_instance_);
}
inline ::ignition::msgs::Wrench* JointWrench::release_body_1_wrench() {
  // @@protoc_insertion_point(field_release:ignition.msgs.JointWrench.body_1_wrench)
  _has_bits_[0] &= ~0x00000008u;
  ::ignition::msgs::Wrench* temp = body_1_wrench_;
  body_1_wrench_ = nullptr;
  return temp;
}
inline ::ignition::msgs::Wrench* JointWrench::mutable_body_1_wrench() {
  _has_bits_[0] |= 0x00000008u;
  if (body_1_wrench_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::Wrench>(GetArenaNoVirtual());
    body_1_wrench_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.JointWrench.body_1_wrench)
  return body_1_wrench_;
}
inline void JointWrench::set_allocated_body_1_wrench(::ignition::msgs::Wrench* body_1_wrench) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(body_1_wrench_);
  }
  if (body_1_wrench) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      body_1_wrench = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, body_1_wrench, submessage_arena);
    }
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  body_1_wrench_ = body_1_wrench;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.JointWrench.body_1_wrench)
}

// optional .ignition.msgs.Wrench body_2_wrench = 7;
inline bool JointWrench::has_body_2_wrench() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline const ::ignition::msgs::Wrench& JointWrench::body_2_wrench() const {
  const ::ignition::msgs::Wrench* p = body_2_wrench_;
  // @@protoc_insertion_point(field_get:ignition.msgs.JointWrench.body_2_wrench)
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::Wrench*>(
      &::ignition::msgs::_Wrench_default_instance_);
}
inline ::ignition::msgs::Wrench* JointWrench::release_body_2_wrench() {
  // @@protoc_insertion_point(field_release:ignition.msgs.JointWrench.body_2_wrench)
  _has_bits_[0] &= ~0x00000010u;
  ::ignition::msgs::Wrench* temp = body_2_wrench_;
  body_2_wrench_ = nullptr;
  return temp;
}
inline ::ignition::msgs::Wrench* JointWrench::mutable_body_2_wrench() {
  _has_bits_[0] |= 0x00000010u;
  if (body_2_wrench_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::Wrench>(GetArenaNoVirtual());
    body_2_wrench_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.JointWrench.body_2_wrench)
  return body_2_wrench_;
}
inline void JointWrench::set_allocated_body_2_wrench(::ignition::msgs::Wrench* body_2_wrench) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(body_2_wrench_);
  }
  if (body_2_wrench) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      body_2_wrench = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, body_2_wrench, submessage_arena);
    }
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  body_2_wrench_ = body_2_wrench;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.JointWrench.body_2_wrench)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

typedef std::unique_ptr<JointWrench> JointWrenchUniquePtr;
typedef std::unique_ptr<const JointWrench> ConstJointWrenchUniquePtr;
typedef std::shared_ptr<JointWrench> JointWrenchSharedPtr;
typedef std::shared_ptr<const JointWrench> ConstJointWrenchSharedPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace ignition

#ifdef _MSC_VER
#pragma warning(pop)
#endif
// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2fjoint_5fwrench_2eproto
