// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ignition/msgs/log_control.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2flog_5fcontrol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2flog_5fcontrol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ignition/msgs/header.pb.h"
#ifndef _MSC_VER
#pragma GCC system_header
#else
#pragma warning(push)
#pragma warning(disable: 4244 4267 4100 4244 4512 4127 4068 4275 4251)
#endif
#include <memory>
#include <ignition/msgs/Export.hh>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ignition_2fmsgs_2flog_5fcontrol_2eproto IGNITION_MSGS_VISIBLE
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct IGNITION_MSGS_VISIBLE TableStruct_ignition_2fmsgs_2flog_5fcontrol_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern IGNITION_MSGS_VISIBLE const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ignition_2fmsgs_2flog_5fcontrol_2eproto;
namespace ignition {
namespace msgs {
class LogControl;
class LogControlDefaultTypeInternal;
IGNITION_MSGS_VISIBLE extern LogControlDefaultTypeInternal _LogControl_default_instance_;
}  // namespace msgs
}  // namespace ignition
PROTOBUF_NAMESPACE_OPEN
template<> IGNITION_MSGS_VISIBLE ::ignition::msgs::LogControl* Arena::CreateMaybeMessage<::ignition::msgs::LogControl>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ignition {
namespace msgs {

// ===================================================================

class IGNITION_MSGS_VISIBLE LogControl :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ignition.msgs.LogControl) */ {
 public:
  LogControl();
  virtual ~LogControl();

  LogControl(const LogControl& from);
  LogControl(LogControl&& from) noexcept
    : LogControl() {
    *this = ::std::move(from);
  }

  inline LogControl& operator=(const LogControl& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogControl& operator=(LogControl&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LogControl& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LogControl* internal_default_instance() {
    return reinterpret_cast<const LogControl*>(
               &_LogControl_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LogControl& a, LogControl& b) {
    a.Swap(&b);
  }
  inline void Swap(LogControl* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LogControl* New() const final {
    return CreateMaybeMessage<LogControl>(nullptr);
  }

  LogControl* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LogControl>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LogControl& from);
  void MergeFrom(const LogControl& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogControl* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ignition.msgs.LogControl";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ignition_2fmsgs_2flog_5fcontrol_2eproto);
    return ::descriptor_table_ignition_2fmsgs_2flog_5fcontrol_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBasePathFieldNumber = 5,
    kEncodingFieldNumber = 6,
    kHeaderFieldNumber = 1,
    kStartFieldNumber = 2,
    kStopFieldNumber = 3,
    kPausedFieldNumber = 4,
  };
  // optional string base_path = 5;
  bool has_base_path() const;
  void clear_base_path();
  const std::string& base_path() const;
  void set_base_path(const std::string& value);
  void set_base_path(std::string&& value);
  void set_base_path(const char* value);
  void set_base_path(const char* value, size_t size);
  std::string* mutable_base_path();
  std::string* release_base_path();
  void set_allocated_base_path(std::string* base_path);

  // optional string encoding = 6;
  bool has_encoding() const;
  void clear_encoding();
  const std::string& encoding() const;
  void set_encoding(const std::string& value);
  void set_encoding(std::string&& value);
  void set_encoding(const char* value);
  void set_encoding(const char* value, size_t size);
  std::string* mutable_encoding();
  std::string* release_encoding();
  void set_allocated_encoding(std::string* encoding);

  // optional .ignition.msgs.Header header = 1;
  bool has_header() const;
  void clear_header();
  const ::ignition::msgs::Header& header() const;
  ::ignition::msgs::Header* release_header();
  ::ignition::msgs::Header* mutable_header();
  void set_allocated_header(::ignition::msgs::Header* header);

  // optional bool start = 2;
  bool has_start() const;
  void clear_start();
  bool start() const;
  void set_start(bool value);

  // optional bool stop = 3;
  bool has_stop() const;
  void clear_stop();
  bool stop() const;
  void set_stop(bool value);

  // optional bool paused = 4;
  bool has_paused() const;
  void clear_paused();
  bool paused() const;
  void set_paused(bool value);

  // @@protoc_insertion_point(class_scope:ignition.msgs.LogControl)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr base_path_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr encoding_;
  ::ignition::msgs::Header* header_;
  bool start_;
  bool stop_;
  bool paused_;
  friend struct ::TableStruct_ignition_2fmsgs_2flog_5fcontrol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LogControl

// optional .ignition.msgs.Header header = 1;
inline bool LogControl::has_header() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline const ::ignition::msgs::Header& LogControl::header() const {
  const ::ignition::msgs::Header* p = header_;
  // @@protoc_insertion_point(field_get:ignition.msgs.LogControl.header)
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::Header*>(
      &::ignition::msgs::_Header_default_instance_);
}
inline ::ignition::msgs::Header* LogControl::release_header() {
  // @@protoc_insertion_point(field_release:ignition.msgs.LogControl.header)
  _has_bits_[0] &= ~0x00000004u;
  ::ignition::msgs::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::ignition::msgs::Header* LogControl::mutable_header() {
  _has_bits_[0] |= 0x00000004u;
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::Header>(GetArenaNoVirtual());
    header_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.LogControl.header)
  return header_;
}
inline void LogControl::set_allocated_header(::ignition::msgs::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.LogControl.header)
}

// optional bool start = 2;
inline bool LogControl::has_start() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void LogControl::clear_start() {
  start_ = false;
  _has_bits_[0] &= ~0x00000008u;
}
inline bool LogControl::start() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.LogControl.start)
  return start_;
}
inline void LogControl::set_start(bool value) {
  _has_bits_[0] |= 0x00000008u;
  start_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.LogControl.start)
}

// optional bool stop = 3;
inline bool LogControl::has_stop() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void LogControl::clear_stop() {
  stop_ = false;
  _has_bits_[0] &= ~0x00000010u;
}
inline bool LogControl::stop() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.LogControl.stop)
  return stop_;
}
inline void LogControl::set_stop(bool value) {
  _has_bits_[0] |= 0x00000010u;
  stop_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.LogControl.stop)
}

// optional bool paused = 4;
inline bool LogControl::has_paused() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void LogControl::clear_paused() {
  paused_ = false;
  _has_bits_[0] &= ~0x00000020u;
}
inline bool LogControl::paused() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.LogControl.paused)
  return paused_;
}
inline void LogControl::set_paused(bool value) {
  _has_bits_[0] |= 0x00000020u;
  paused_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.LogControl.paused)
}

// optional string base_path = 5;
inline bool LogControl::has_base_path() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LogControl::clear_base_path() {
  base_path_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& LogControl::base_path() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.LogControl.base_path)
  return base_path_.GetNoArena();
}
inline void LogControl::set_base_path(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  base_path_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ignition.msgs.LogControl.base_path)
}
inline void LogControl::set_base_path(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  base_path_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ignition.msgs.LogControl.base_path)
}
inline void LogControl::set_base_path(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  base_path_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ignition.msgs.LogControl.base_path)
}
inline void LogControl::set_base_path(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  base_path_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ignition.msgs.LogControl.base_path)
}
inline std::string* LogControl::mutable_base_path() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:ignition.msgs.LogControl.base_path)
  return base_path_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* LogControl::release_base_path() {
  // @@protoc_insertion_point(field_release:ignition.msgs.LogControl.base_path)
  if (!has_base_path()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return base_path_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void LogControl::set_allocated_base_path(std::string* base_path) {
  if (base_path != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  base_path_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), base_path);
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.LogControl.base_path)
}

// optional string encoding = 6;
inline bool LogControl::has_encoding() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LogControl::clear_encoding() {
  encoding_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& LogControl::encoding() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.LogControl.encoding)
  return encoding_.GetNoArena();
}
inline void LogControl::set_encoding(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  encoding_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ignition.msgs.LogControl.encoding)
}
inline void LogControl::set_encoding(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  encoding_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ignition.msgs.LogControl.encoding)
}
inline void LogControl::set_encoding(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  encoding_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ignition.msgs.LogControl.encoding)
}
inline void LogControl::set_encoding(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  encoding_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ignition.msgs.LogControl.encoding)
}
inline std::string* LogControl::mutable_encoding() {
  _has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_mutable:ignition.msgs.LogControl.encoding)
  return encoding_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* LogControl::release_encoding() {
  // @@protoc_insertion_point(field_release:ignition.msgs.LogControl.encoding)
  if (!has_encoding()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return encoding_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void LogControl::set_allocated_encoding(std::string* encoding) {
  if (encoding != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  encoding_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), encoding);
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.LogControl.encoding)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

typedef std::unique_ptr<LogControl> LogControlUniquePtr;
typedef std::unique_ptr<const LogControl> ConstLogControlUniquePtr;
typedef std::shared_ptr<LogControl> LogControlSharedPtr;
typedef std::shared_ptr<const LogControl> ConstLogControlSharedPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace ignition

#ifdef _MSC_VER
#pragma warning(pop)
#endif
// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2flog_5fcontrol_2eproto
