// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ignition/msgs/sonar.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2fsonar_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2fsonar_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ignition/msgs/pose.pb.h"
#include "ignition/msgs/vector3d.pb.h"
#include "ignition/msgs/header.pb.h"
#ifndef _MSC_VER
#pragma GCC system_header
#else
#pragma warning(push)
#pragma warning(disable: 4244 4267 4100 4244 4512 4127 4068 4275 4251)
#endif
#include <memory>
#include <ignition/msgs/Export.hh>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ignition_2fmsgs_2fsonar_2eproto IGNITION_MSGS_VISIBLE
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct IGNITION_MSGS_VISIBLE TableStruct_ignition_2fmsgs_2fsonar_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern IGNITION_MSGS_VISIBLE const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ignition_2fmsgs_2fsonar_2eproto;
namespace ignition {
namespace msgs {
class Sonar;
class SonarDefaultTypeInternal;
IGNITION_MSGS_VISIBLE extern SonarDefaultTypeInternal _Sonar_default_instance_;
}  // namespace msgs
}  // namespace ignition
PROTOBUF_NAMESPACE_OPEN
template<> IGNITION_MSGS_VISIBLE ::ignition::msgs::Sonar* Arena::CreateMaybeMessage<::ignition::msgs::Sonar>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ignition {
namespace msgs {

// ===================================================================

class IGNITION_MSGS_VISIBLE Sonar :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ignition.msgs.Sonar) */ {
 public:
  Sonar();
  virtual ~Sonar();

  Sonar(const Sonar& from);
  Sonar(Sonar&& from) noexcept
    : Sonar() {
    *this = ::std::move(from);
  }

  inline Sonar& operator=(const Sonar& from) {
    CopyFrom(from);
    return *this;
  }
  inline Sonar& operator=(Sonar&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Sonar& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Sonar* internal_default_instance() {
    return reinterpret_cast<const Sonar*>(
               &_Sonar_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Sonar& a, Sonar& b) {
    a.Swap(&b);
  }
  inline void Swap(Sonar* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Sonar* New() const final {
    return CreateMaybeMessage<Sonar>(nullptr);
  }

  Sonar* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Sonar>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Sonar& from);
  void MergeFrom(const Sonar& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Sonar* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ignition.msgs.Sonar";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ignition_2fmsgs_2fsonar_2eproto);
    return ::descriptor_table_ignition_2fmsgs_2fsonar_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFrameFieldNumber = 2,
    kHeaderFieldNumber = 1,
    kWorldPoseFieldNumber = 3,
    kContactFieldNumber = 8,
    kRangeMinFieldNumber = 4,
    kRangeMaxFieldNumber = 5,
    kRadiusFieldNumber = 6,
    kRangeFieldNumber = 7,
  };
  // optional string frame = 2;
  bool has_frame() const;
  void clear_frame();
  const std::string& frame() const;
  void set_frame(const std::string& value);
  void set_frame(std::string&& value);
  void set_frame(const char* value);
  void set_frame(const char* value, size_t size);
  std::string* mutable_frame();
  std::string* release_frame();
  void set_allocated_frame(std::string* frame);

  // optional .ignition.msgs.Header header = 1;
  bool has_header() const;
  void clear_header();
  const ::ignition::msgs::Header& header() const;
  ::ignition::msgs::Header* release_header();
  ::ignition::msgs::Header* mutable_header();
  void set_allocated_header(::ignition::msgs::Header* header);

  // optional .ignition.msgs.Pose world_pose = 3;
  bool has_world_pose() const;
  void clear_world_pose();
  const ::ignition::msgs::Pose& world_pose() const;
  ::ignition::msgs::Pose* release_world_pose();
  ::ignition::msgs::Pose* mutable_world_pose();
  void set_allocated_world_pose(::ignition::msgs::Pose* world_pose);

  // optional .ignition.msgs.Vector3d contact = 8;
  bool has_contact() const;
  void clear_contact();
  const ::ignition::msgs::Vector3d& contact() const;
  ::ignition::msgs::Vector3d* release_contact();
  ::ignition::msgs::Vector3d* mutable_contact();
  void set_allocated_contact(::ignition::msgs::Vector3d* contact);

  // optional double range_min = 4;
  bool has_range_min() const;
  void clear_range_min();
  double range_min() const;
  void set_range_min(double value);

  // optional double range_max = 5;
  bool has_range_max() const;
  void clear_range_max();
  double range_max() const;
  void set_range_max(double value);

  // optional double radius = 6;
  bool has_radius() const;
  void clear_radius();
  double radius() const;
  void set_radius(double value);

  // optional double range = 7;
  bool has_range() const;
  void clear_range();
  double range() const;
  void set_range(double value);

  // @@protoc_insertion_point(class_scope:ignition.msgs.Sonar)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr frame_;
  ::ignition::msgs::Header* header_;
  ::ignition::msgs::Pose* world_pose_;
  ::ignition::msgs::Vector3d* contact_;
  double range_min_;
  double range_max_;
  double radius_;
  double range_;
  friend struct ::TableStruct_ignition_2fmsgs_2fsonar_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Sonar

// optional .ignition.msgs.Header header = 1;
inline bool Sonar::has_header() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline const ::ignition::msgs::Header& Sonar::header() const {
  const ::ignition::msgs::Header* p = header_;
  // @@protoc_insertion_point(field_get:ignition.msgs.Sonar.header)
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::Header*>(
      &::ignition::msgs::_Header_default_instance_);
}
inline ::ignition::msgs::Header* Sonar::release_header() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Sonar.header)
  _has_bits_[0] &= ~0x00000002u;
  ::ignition::msgs::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::ignition::msgs::Header* Sonar::mutable_header() {
  _has_bits_[0] |= 0x00000002u;
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::Header>(GetArenaNoVirtual());
    header_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Sonar.header)
  return header_;
}
inline void Sonar::set_allocated_header(::ignition::msgs::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Sonar.header)
}

// optional string frame = 2;
inline bool Sonar::has_frame() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Sonar::clear_frame() {
  frame_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Sonar::frame() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Sonar.frame)
  return frame_.GetNoArena();
}
inline void Sonar::set_frame(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  frame_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Sonar.frame)
}
inline void Sonar::set_frame(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  frame_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ignition.msgs.Sonar.frame)
}
inline void Sonar::set_frame(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  frame_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ignition.msgs.Sonar.frame)
}
inline void Sonar::set_frame(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  frame_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ignition.msgs.Sonar.frame)
}
inline std::string* Sonar::mutable_frame() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Sonar.frame)
  return frame_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Sonar::release_frame() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Sonar.frame)
  if (!has_frame()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return frame_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Sonar::set_allocated_frame(std::string* frame) {
  if (frame != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  frame_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), frame);
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Sonar.frame)
}

// optional .ignition.msgs.Pose world_pose = 3;
inline bool Sonar::has_world_pose() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline const ::ignition::msgs::Pose& Sonar::world_pose() const {
  const ::ignition::msgs::Pose* p = world_pose_;
  // @@protoc_insertion_point(field_get:ignition.msgs.Sonar.world_pose)
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::Pose*>(
      &::ignition::msgs::_Pose_default_instance_);
}
inline ::ignition::msgs::Pose* Sonar::release_world_pose() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Sonar.world_pose)
  _has_bits_[0] &= ~0x00000004u;
  ::ignition::msgs::Pose* temp = world_pose_;
  world_pose_ = nullptr;
  return temp;
}
inline ::ignition::msgs::Pose* Sonar::mutable_world_pose() {
  _has_bits_[0] |= 0x00000004u;
  if (world_pose_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::Pose>(GetArenaNoVirtual());
    world_pose_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Sonar.world_pose)
  return world_pose_;
}
inline void Sonar::set_allocated_world_pose(::ignition::msgs::Pose* world_pose) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(world_pose_);
  }
  if (world_pose) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      world_pose = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, world_pose, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  world_pose_ = world_pose;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Sonar.world_pose)
}

// optional double range_min = 4;
inline bool Sonar::has_range_min() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Sonar::clear_range_min() {
  range_min_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline double Sonar::range_min() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Sonar.range_min)
  return range_min_;
}
inline void Sonar::set_range_min(double value) {
  _has_bits_[0] |= 0x00000010u;
  range_min_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.Sonar.range_min)
}

// optional double range_max = 5;
inline bool Sonar::has_range_max() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Sonar::clear_range_max() {
  range_max_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline double Sonar::range_max() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Sonar.range_max)
  return range_max_;
}
inline void Sonar::set_range_max(double value) {
  _has_bits_[0] |= 0x00000020u;
  range_max_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.Sonar.range_max)
}

// optional double radius = 6;
inline bool Sonar::has_radius() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Sonar::clear_radius() {
  radius_ = 0;
  _has_bits_[0] &= ~0x00000040u;
}
inline double Sonar::radius() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Sonar.radius)
  return radius_;
}
inline void Sonar::set_radius(double value) {
  _has_bits_[0] |= 0x00000040u;
  radius_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.Sonar.radius)
}

// optional double range = 7;
inline bool Sonar::has_range() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Sonar::clear_range() {
  range_ = 0;
  _has_bits_[0] &= ~0x00000080u;
}
inline double Sonar::range() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Sonar.range)
  return range_;
}
inline void Sonar::set_range(double value) {
  _has_bits_[0] |= 0x00000080u;
  range_ = value;
  // @@protoc_insertion_point(field_set:ignition.msgs.Sonar.range)
}

// optional .ignition.msgs.Vector3d contact = 8;
inline bool Sonar::has_contact() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline const ::ignition::msgs::Vector3d& Sonar::contact() const {
  const ::ignition::msgs::Vector3d* p = contact_;
  // @@protoc_insertion_point(field_get:ignition.msgs.Sonar.contact)
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::Vector3d*>(
      &::ignition::msgs::_Vector3d_default_instance_);
}
inline ::ignition::msgs::Vector3d* Sonar::release_contact() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Sonar.contact)
  _has_bits_[0] &= ~0x00000008u;
  ::ignition::msgs::Vector3d* temp = contact_;
  contact_ = nullptr;
  return temp;
}
inline ::ignition::msgs::Vector3d* Sonar::mutable_contact() {
  _has_bits_[0] |= 0x00000008u;
  if (contact_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::Vector3d>(GetArenaNoVirtual());
    contact_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Sonar.contact)
  return contact_;
}
inline void Sonar::set_allocated_contact(::ignition::msgs::Vector3d* contact) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(contact_);
  }
  if (contact) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      contact = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, contact, submessage_arena);
    }
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  contact_ = contact;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Sonar.contact)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

typedef std::unique_ptr<Sonar> SonarUniquePtr;
typedef std::unique_ptr<const Sonar> ConstSonarUniquePtr;
typedef std::shared_ptr<Sonar> SonarSharedPtr;
typedef std::shared_ptr<const Sonar> ConstSonarSharedPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace ignition

#ifdef _MSC_VER
#pragma warning(pop)
#endif
// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2fsonar_2eproto
